package selectcontract;

import java.io.BufferedWriter;
import java.io.FileWriter;
import javax.swing.JOptionPane;




/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author manuel
 */
public class NewContract extends javax.swing.JDialog {

    private ContractModel theContracts;

    /**
     * Creates new form NewContract
     */
    public NewContract(java.awt.Frame parent, boolean modal, ContractModel theContracts) {
        super(parent, modal);
        initComponents();
        this.theContracts = theContracts;
        settingComboBox(); 
    }    
      
    private void settingComboBox(){
        jOriginComboBox.setModel(new javax.swing.DefaultComboBoxModel<>
        (new String[] { "","Victoria", "Vancouver", "Seattle", "Nanaimo", "Prince George" }));
        
        jDestComboBox.setModel(new javax.swing.DefaultComboBoxModel<>
        (new String[] {"" ,"Victoria", "Vancouver", "Seattle", "Nanaimo", "Prince George"}));
        
    
    }
    
    private boolean isValidContractID(String id){
        
        boolean theTruth = true;
        
        // validates if the input is 4 characters
        if (id.length() != 4){
            theTruth = false;
            JOptionPane.showMessageDialog(this, "Error: not enough character");
        } else if (!Character.isDigit(id.charAt(0))) {
            theTruth = false;
            JOptionPane.showMessageDialog(this, "Error: First chracter need to be a number");
        } else {
            // check if the other charactes are letters
            for(int i = 1; i < 4; i++){
                char c = id.charAt(i);
                if (!Character.isLetter(c)){
                    theTruth = false;
                    JOptionPane.showMessageDialog(this, "Error: There is more than one number");
                }
            }
        }
        
       if(theContracts.containsId(id)){
           theTruth = false;
           JOptionPane.showMessageDialog(this, "Error: There is duplication");
       }
        
        
        
        return theTruth;
    }
    
    private boolean isLocationValid(String origin, String destination){
        boolean validLocation = true;
                
        if (origin.equals(destination)){
            validLocation = false;
            JOptionPane.showMessageDialog(this, 
                    "Error Destination: Destination and Origin are the same location");
        }
    
    return validLocation;
    }
    
    private boolean isValidOrderItem(String order){
        boolean orderValid = true;
        
        if (order.contains(",") || !order.chars().allMatch(Character::isLetter)){
            orderValid = false;
            JOptionPane.showMessageDialog(this,
                    "Error Order Item: contains a comma or numbers");
        }
        if(order.equals("")){
            orderValid = false;
            JOptionPane.showMessageDialog(this,"Error Order Item: is empty");
        }
        
    return orderValid;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCancelButton = new javax.swing.JButton();
        jSaveButton = new javax.swing.JButton();
        jTextContractID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jOriginComboBox = new javax.swing.JComboBox<>();
        jDestComboBox = new javax.swing.JComboBox<>();
        jTextOrderItem = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jRestButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Enter New Contract");
        setAlwaysOnTop(true);

        jLabel1.setText("Contract ID");

        jCancelButton.setText("Cancel");
        jCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelButtonActionPerformed(evt);
            }
        });

        jSaveButton.setText("Save");
        jSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveButtonActionPerformed(evt);
            }
        });

        jTextContractID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextContractIDActionPerformed(evt);
            }
        });

        jLabel2.setText("Origin");

        jLabel3.setText("Destination");

        jOriginComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jDestComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextOrderItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextOrderItemActionPerformed(evt);
            }
        });

        jLabel4.setText("Order Item");

        jRestButton.setText("Rest");
        jRestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRestButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextContractID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(32, 32, 32))
                    .addComponent(jOriginComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jDestComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextOrderItem, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jSaveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRestButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCancelButton)
                .addContainerGap(184, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(jOriginComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(jDestComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextContractID))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTextOrderItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSaveButton)
                    .addComponent(jCancelButton)
                    .addComponent(jRestButton))
                .addGap(99, 99, 99))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        System.out.println("Exit the display");
    }//GEN-LAST:event_jCancelButtonActionPerformed

    private void jSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveButtonActionPerformed
        // TODO add your handling code here:
        // validate the Contract ID
        String contractID = jTextContractID.getText().toUpperCase();      
        boolean contractAnswer = isValidContractID(contractID);
        
        String origin = (String) jOriginComboBox.getSelectedItem();
        String destination = (String) jDestComboBox.getSelectedItem();
        boolean locations = isLocationValid(origin, destination);
        
        String orderItem = jTextOrderItem.getText();
        boolean orderItemAnswer = isValidOrderItem(orderItem);
        
        System.out.println(contractID + ", " + origin + ", " + destination + ", " + orderItem);
        
        
//         add the other buttons
        if (contractAnswer && locations && orderItemAnswer){
//            String fileName = "/Users/manuel/Desktop/Select_Contract7/src/selectcontract/contracts.txt";
            String fileName = "E:\\Select_Contract7\\src\\selectcontract\\contracts.txt";
            
            try {
                BufferedWriter writer = new BufferedWriter(new FileWriter(fileName, true));
                writer.write(contractID + "," + origin + "," + destination + "," + orderItem);
                writer.newLine();
                writer.close();
                
            } catch (Exception ex) {
                System.out.println(ex);
            
            }
            
            System.out.println("clear");
        } else {
            System.out.println("not clear");
        }
       
       
    }//GEN-LAST:event_jSaveButtonActionPerformed
    
    
    private void jTextContractIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextContractIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextContractIDActionPerformed

    private void jTextOrderItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextOrderItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextOrderItemActionPerformed

    private void jRestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRestButtonActionPerformed
        // TODO add your handling code here:
        jTextContractID.setText("");
        jTextOrderItem.setText("");
        
        jDestComboBox.setModel(new javax.swing.DefaultComboBoxModel<>
        (new String[] {"" ,"Victoria", "Vancouver", "Seattle", "Nanaimo", "Prince George"}));
        
        jOriginComboBox.setModel(new javax.swing.DefaultComboBoxModel<>
        (new String[] { "","Victoria", "Vancouver", "Seattle", "Nanaimo", "Prince George" }));
        
        
    }//GEN-LAST:event_jRestButtonActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(NewContract.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(NewContract.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(NewContract.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(NewContract.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                NewContract dialog = new NewContract(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCancelButton;
    private javax.swing.JComboBox<String> jDestComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> jOriginComboBox;
    private javax.swing.JButton jRestButton;
    private javax.swing.JButton jSaveButton;
    private javax.swing.JTextField jTextContractID;
    private javax.swing.JTextField jTextOrderItem;
    // End of variables declaration//GEN-END:variables
}
